#############################################################################
# Makefile for building: MyXPDF
# Generated by qmake (3.0) (Qt 5.0.1) on: Fri Apr 12 10:44:10 2013
# Project:  MyXPDF.pro
# Template: subdirs
# Command: /home/mrsoul/Qt5.0.1/5.0.1/gcc_64/bin/qmake -spec linux-g++-64 -o Makefile MyXPDF.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /home/mrsoul/Qt5.0.1/5.0.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-Freetype \
		sub-Xpdf \
		sub-Viewer


sub-Freetype-qmake_all:  FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile
	cd Freetype/ && $(MAKE) -f Makefile qmake_all
sub-Freetype: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile
sub-Freetype-make_first-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Freetype-make_first: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Freetype-all-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Freetype-all: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Freetype-clean-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Freetype-clean: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Freetype-distclean-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Freetype-distclean: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Freetype-install_subtargets-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Freetype-install_subtargets: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Freetype-uninstall_subtargets-ordered: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Freetype-uninstall_subtargets: FORCE
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Xpdf-qmake_all: sub-Freetype-qmake_all FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile
	cd Xpdf/ && $(MAKE) -f Makefile qmake_all
sub-Xpdf: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile
sub-Xpdf-make_first-ordered: sub-Freetype-make_first-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Xpdf-make_first: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Xpdf-all-ordered: sub-Freetype-all-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Xpdf-all: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Xpdf-clean-ordered: sub-Freetype-clean-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Xpdf-clean: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Xpdf-distclean-ordered: sub-Freetype-distclean-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Xpdf-distclean: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Xpdf-install_subtargets-ordered: sub-Freetype-install_subtargets-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Xpdf-install_subtargets: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Xpdf-uninstall_subtargets-ordered: sub-Freetype-uninstall_subtargets-ordered  FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Xpdf-uninstall_subtargets: FORCE
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Viewer-qmake_all: sub-Xpdf-qmake_all FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile
	cd Viewer/ && $(MAKE) -f Makefile qmake_all
sub-Viewer: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile
sub-Viewer-make_first-ordered: sub-Xpdf-make_first-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Viewer-make_first: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile 
sub-Viewer-all-ordered: sub-Xpdf-all-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Viewer-all: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile all
sub-Viewer-clean-ordered: sub-Xpdf-clean-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Viewer-clean: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile clean
sub-Viewer-distclean-ordered: sub-Xpdf-distclean-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Viewer-distclean: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Viewer-install_subtargets-ordered: sub-Xpdf-install_subtargets-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Viewer-install_subtargets: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile install
sub-Viewer-uninstall_subtargets-ordered: sub-Xpdf-uninstall_subtargets-ordered  FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Viewer-uninstall_subtargets: FORCE
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: MyXPDF.pro ../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf ../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/shell-unix.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/unix.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/linux.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/qconfig.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_v8.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_post.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/default_pre.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/release.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_post.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/shared.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/wayland-scanner.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/yacc.prf \
		../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/lex.prf \
		MyXPDF.pro
	$(QMAKE) -spec linux-g++-64 -o Makefile MyXPDF.pro
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/shell-unix.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/unix.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/linux.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-base.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/common/g++-unix.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/qconfig.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_bootstrap.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_clucene.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_designercomponents.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_platformsupport.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_quickparticles.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_v8.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/qt_config.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/linux-g++-64/qmake.conf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/spec_post.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_pre.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/default_pre.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/release.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/default_post.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/shared.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/warn_on.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/wayland-scanner.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/exceptions.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/yacc.prf:
../../../../../Qt5.0.1/5.0.1/gcc_64/mkspecs/features/lex.prf:
MyXPDF.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile MyXPDF.pro

qmake_all: sub-Freetype-qmake_all sub-Xpdf-qmake_all sub-Viewer-qmake_all FORCE

make_first: sub-Freetype-make_first-ordered sub-Xpdf-make_first-ordered sub-Viewer-make_first-ordered FORCE
all: sub-Freetype-all-ordered sub-Xpdf-all-ordered sub-Viewer-all-ordered FORCE
clean: sub-Freetype-clean-ordered sub-Xpdf-clean-ordered sub-Viewer-clean-ordered FORCE
distclean: sub-Freetype-distclean-ordered sub-Xpdf-distclean-ordered sub-Viewer-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Freetype-install_subtargets-ordered sub-Xpdf-install_subtargets-ordered sub-Viewer-install_subtargets-ordered FORCE
uninstall_subtargets: sub-Freetype-uninstall_subtargets-ordered sub-Xpdf-uninstall_subtargets-ordered sub-Viewer-uninstall_subtargets-ordered FORCE

sub-Freetype-check_ordered:
	@test -d Freetype/ || $(MKDIR) Freetype/ 
	cd Freetype/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Freetype/Freetype.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile check
sub-Xpdf-check_ordered: sub-Freetype-check_ordered 
	@test -d Xpdf/ || $(MKDIR) Xpdf/ 
	cd Xpdf/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Xpdf/Xpdf.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile check
sub-Viewer-check_ordered: sub-Xpdf-check_ordered 
	@test -d Viewer/ || $(MKDIR) Viewer/ 
	cd Viewer/ && ( test -f Makefile || $(QMAKE) /home/mrsoul/Dropbox/Development/Qt/send/source/Viewer/Viewer.pro -spec linux-g++-64 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-Freetype-check_ordered sub-Xpdf-check_ordered sub-Viewer-check_ordered
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

